dist: trusty
language: java
jdk:
  - openjdk7
  - oraclejdk8
env:
  - CRATE_VERSION=0.56.4
  - CRATE_VERSION=0.57.6
  - CRATE_VERSION=1.0.1
  - CRATE_VERSION=2.1.6

matrix:
  exclude:
    - jdk: openjdk7
      env: CRATE_VERSION=1.0.1
    - jdk: openjdk7
      env: CRATE_VERSION=2.1.6

cache:
  directories:
    - $HOME/.m2

sudo: false

# Workaround for https://github.com/gradle/gradle/issues/2421
install:
  - JAVA_HOME=$(jdk_switcher home openjdk8) ./gradlew classes testClasses

script: ./gradlew test -s

notifications:
  email: false
